const imgBaseUrl = process.env.IMAGE_BASE_URL;
const MovingAverageCrossoverValue = [
  {
    'title': 'Close Crossing SMA',
    'data': [
      {
        'label': 'Close Crossing 20 SMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-s20.svg',
        'defaultValue': false,
        'field': '_20_day_sma_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': 'Close Crossing 20 SMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-s20.svg',
        'defaultValue': false,
        'field': '_20_day_sma_above',
        'name': 'moving-average-crossovers',
      },
      {
        'label': 'Close Crossing 50 SMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-s50.svg',
        'defaultValue': false,
        'field': '_50_day_sma_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': 'Close Crossing 50 SMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-s100.svg',
        'defaultValue': false,
        'field': '_50_day_sma_above',
        'name': 'moving-average-crossovers',
      },
      {
        'label': 'Close Crossing 100 SMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-s100.svg',
        'defaultValue': false,
        'field': '_100_day_sma_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': 'Close Crossing 100 SMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-s100.svg',
        'defaultValue': false,
        'field': '_100_day_sma_above',
        'name': 'moving-average-crossovers',
      },
      {
        'label': 'Close Crossing 200 SMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-s200.svg',
        'defaultValue': false,
        'field': '_200_day_sma_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': 'Close Crossing 200 SMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-s200.svg',
        'defaultValue': false,
        'field': '_200_day_sma_above',
        'name': 'moving-average-crossovers',
      },
    ],
  },
  {
    'title': 'Close Crossing EMA',
    'data': [
      {
        'label': 'Close Crossing 5 EMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-e5.svg',
        'defaultValue': false,
        'field': '_5_day_ema_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': 'Close Crossing 5 EMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-e5.svg',
        'defaultValue': false,
        'field': '_5_day_ema_above',
        'name': 'moving-average-crossovers',
      },
      {
        'label': 'Close Crossing 8 EMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-e8.svg',
        'defaultValue': false,
        'field': '_8_day_ema_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': 'Close Crossing 8 EMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-e8.svg',
        'defaultValue': false,
        'field': '_8_day_ema_above',
        'name': 'moving-average-crossovers',
      },
      {
        'label': 'Close Crossing 20 EMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-e20.svg',
        'defaultValue': false,
        'field': '_20_day_ema_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': 'Close Crossing 20 EMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-e20.svg',
        'defaultValue': false,
        'field': '_20_day_ema_above',
        'name': 'moving-average-crossovers',
      },
      {
        'label': 'Close Crossing 26 EMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-e26.svg',
        'defaultValue': false,
        'field': '_26_day_ema_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': 'Close Crossing 26 EMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-e26.svg',
        'defaultValue': false,
        'field': '_26_day_ema_above',
        'name': 'moving-average-crossovers',
      },
      {
        'label': 'Close Crossing 50 EMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-e50.svg',
        'defaultValue': false,
        'field': '_50_day_ema_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': 'Close Crossing 50 EMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-e50.svg',
        'defaultValue': false,
        'field': '_50_day_ema_above',
        'name': 'moving-average-crossovers',
      },
      {
        'label': 'Close Crossing 200 EMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-e200.svg',
        'defaultValue': false,
        'field': '_200_day_ema_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': 'Close Crossing 200 EMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-e200.svg',
        'defaultValue': false,
        'field': '_200_day_ema_above',
        'name': 'moving-average-crossovers',
      },
    ],
  },
  {
    'title': 'SMA Crossing SMA',
    'data': [
      {
        'label': '5 SMA Crossing 20 SMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-s5-s20.svg',
        'defaultValue': false,
        'field': '_5_20_sma_crossover_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '5 SMA Crossing 20 SMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-s5-s20.svg',
        'defaultValue': false,
        'field': '_5_20_sma_crossover_above',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '20 SMA Crossing 50 SMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-s20-s50.svg',
        'defaultValue': false,
        'field': '_20_50_sma_crossover_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '20 SMA Crossing 50 SMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-s20-s50.svg',
        'defaultValue': false,
        'field': '_20_50_sma_crossover_above',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '20 SMA Crossing 100 SMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-s20-s100.svg',
        'defaultValue': false,
        'field': '_20_100_sma_crossover_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '20 SMA Crossing 100 SMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-s20-s100.svg',
        'defaultValue': false,
        'field': '_20_100_sma_crossover_above',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '50 SMA Crossing 100 SMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-s50-s100.svg',
        'defaultValue': false,
        'field': '_50_100_sma_crossover_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '50 SMA Crossing 100 SMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-s50-s100.svg',
        'defaultValue': false,
        'field': '_50_100_sma_crossover_above',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '50 SMA Crossing 200 SMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-s50-s200.svg',
        'defaultValue': false,
        'field': '_50_200_sma_crossover_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '50 SMA Crossing 200 SMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-s50-s200.svg',
        'defaultValue': false,
        'field': '_50_200_sma_crossover_above',
        'name': 'moving-average-crossovers',
      },
    ],
  },
  {
    'title': 'EMA Crossing EMA',
    'data': [
      {
        'label': '5 EMA Crossing 20 EMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-e5-e20.svg',
        'defaultValue': false,
        'field': '_5_20_ema_crossover_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '5 EMA Crossing 20 EMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-e5-e20.svg',
        'defaultValue': false,
        'field': '_5_20_ema_crossover_above',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '8 EMA Crossing 20 EMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-e8-e20.svg',
        'defaultValue': false,
        'field': '_8_20_ema_crossover_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '8 EMA Crossing 20 EMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-e8-e20.svg',
        'defaultValue': false,
        'field': '_8_20_ema_crossover_above',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '12 EMA Crossing 26 EMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-e12-e26.svg',
        'defaultValue': false,
        'field': '_12_26_ema_crossover_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '12 EMA Crossing 26 EMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-e12-e26.svg',
        'defaultValue': false,
        'field': '_12_26_ema_crossover_above',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '9 EMA Crossing 30 EMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-e9-e30.svg',
        'defaultValue': false,
        'field': '_9_30_ema_crossover_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '9 EMA Crossing 30 EMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-e9-e30.svg',
        'defaultValue': false,
        'field': '_9_30_ema_crossover_above',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '20 EMA Crossing 50 EMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-e20-e50.svg',
        'defaultValue': false,
        'field': '_20_50_ema_crossover_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '20 EMA Crossing 50 EMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-e20-e50.svg',
        'defaultValue': false,
        'field': '_20_50_ema_crossover_above',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '50 EMA Crossing 200 EMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-e50-e200.svg',
        'defaultValue': false,
        'field': '_50_200_ema_crossover_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '50 EMA Crossing 200 EMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-e50-e200.svg',
        'defaultValue': false,
        'field': '_50_200_ema_crossover_above',
        'name': 'moving-average-crossovers',
      },
    ],
  },
  {
    'title': 'EMA Crossing SMA',
    'data': [
      {
        'label': '5 EMA Crossing 20 SMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-e5-s20.svg',
        'defaultValue': false,
        'field': 'ema5_sma20_cross_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '5 EMA Crossing 20 SMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-e5-s20.svg',
        'defaultValue': false,
        'field': 'ema5_sma20_cross_above',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '20 EMA Crossing 50 SMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-e20-s50.svg',
        'defaultValue': false,
        'field': 'ema20_sma50_cross_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '20 EMA Crossing 50 SMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-e20-s50.svg',
        'defaultValue': false,
        'field': 'ema20_sma50_cross_above',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '50 EMA Crossing 100 SMA from Below',
        'imgPath': imgBaseUrl+'images/advance-stock/up-e50-s100.svg',
        'defaultValue': false,
        'field': 'ema50_sma100_cross_below',
        'name': 'moving-average-crossovers',
      },
      {
        'label': '50 EMA Crossing 100 SMA from Above',
        'imgPath': imgBaseUrl+'images/advance-stock/down-e50-s100.svg',
        'defaultValue': false,
        'field': 'ema50_sma100_cross_above',
        'name': 'moving-average-crossovers',
      },
    ],
  },
];

export default MovingAverageCrossoverValue;
