const imgBaseUrl = process.env.IMAGE_BASE_URL;
const PriceActionVolumeValue = [
  {
    'title': 'Price Change',
    'data': [
      {
        'label': 'Gainers',
        'imgPath': imgBaseUrl+'images/advance-stock/Price-Change_Close-Gainers.svg',
        'defaultValue': false,
        'field': 'close_gainers',
        'name': 'price-change',
      },
      {
        'label': 'Losers',
        'imgPath': imgBaseUrl+'images/advance-stock/Price-Change_Close-Losers.svg',
        'defaultValue': false,
        'field': 'close_losers',
        'name': 'price-change',
      },
      {
        'label': 'More than 5% Gain',
        'imgPath': imgBaseUrl+'images/advance-stock/Price-Change_Close-More-than5-Gain.svg',
        'defaultValue': false,
        'field': 'close_more_5_gain',
        'name': 'price-change',
      },
      {
        'label': 'More than 5% Down',
        'imgPath': imgBaseUrl+'images/advance-stock/Price-Change_Close-More-than-5-Down.svg',
        'defaultValue': false,
        'field': 'close_more_5_down',
        'name': 'price-change',
      },
    ],
  },
  {
    'title': 'Opening & Closing Price Clues',
    'data': [
      {
        'label': 'Same Open & High',
        'imgPath': imgBaseUrl+'images/advance-stock/Opening-Closing-Price-Clues_Same-Open-High.svg',
        'defaultValue': false,
        'field': 'same_approx_open_high',
        'name': 'opening-closing-pirce-clues',
      },
      {
        'label': 'Same Open & Low',
        'imgPath': imgBaseUrl+'images/advance-stock/Opening-Closing-Price-Clues_Same-Open-Low.svg',
        'defaultValue': false,
        'field': 'same_approx_open_low',
        'name': 'opening-closing-pirce-clues',
      },
      {
        'label': 'Same Open & High (Exact)',
        'imgPath': imgBaseUrl+'images/advance-stock/Opening-Closing-Price-Clues_Same-Open-High.svg',
        'defaultValue': false,
        'field': 'same_open_high',
        'name': 'opening-closing-pirce-clues',
      },
      {
        'label': 'Same Open & Low (Exact)',
        'imgPath': imgBaseUrl+'images/advance-stock/Opening-Closing-Price-Clues_Same-Open-Low.svg',
        'defaultValue': false,
        'field': 'same_open_low',
        'name': 'opening-closing-pirce-clues',
      },
      {
        'label': 'Close Near Day High',
        'imgPath': imgBaseUrl+'images/advance-stock/Opening-Closing-Price-Clues_Close-Near-Day-High.svg',
        'defaultValue': false,
        'field': 'close_nearday_high',
        'name': 'opening-closing-pirce-clues',
      },
      {
        'label': 'Close Near Day Low',
        'imgPath': imgBaseUrl+'images/advance-stock/Opening-Closing-Price-Clues_Close-Near-Day-Low.svg',
        'defaultValue': false,
        'field': 'close_nearday_low',
        'name': 'opening-closing-pirce-clues',
      },
      {
        'label': 'Close Near Open',
        'imgPath': imgBaseUrl+'images/advance-stock/Opening-Closing-Price-Clues_Close-Near-Open.svg',
        'defaultValue': false,
        'field': 'close_near_open',
        'name': 'opening-closing-pirce-clues',
      },
    ],
  },
  {
    'title': 'Candlestick',
    'data': [
      {
        'label': 'Higher High',
        'imgPath': imgBaseUrl+'images/advance-stock/Candlestick_Higher-High.svg',
        'defaultValue': false,
        'field': 'higher_high',
        'name': 'candlestick',
      },
      {
        'label': 'Higher Low',
        'imgPath': imgBaseUrl+'images/advance-stock/Candlestick_Higher-Low.svg',
        'defaultValue': false,
        'field': 'higher_low',
        'name': 'candlestick',
      },
      {
        'label': 'Higher High Higher Low',
        'imgPath': imgBaseUrl+'images/advance-stock/Candlestick-Higher-High-Higher-Low.svg',
        'defaultValue': false,
        'field': 'higher_high_higher_low',
        'name': 'candlestick',
      },
      {
        'label': 'Lower High',
        'imgPath': imgBaseUrl+'images/advance-stock/Candlestick-Higher-High-Higher-Low.svg',
        'defaultValue': false,
        'field': 'lower_high',
        'name': 'candlestick',
      },
      {
        'label': 'Lower Low',
        'imgPath': imgBaseUrl+'images/advance-stock/Candlestick_Lower-Low.svg',
        'defaultValue': false,
        'field': 'lower_low',
        'name': 'candlestick',
      },
      {
        'label': 'Lower High Lower Low',
        'imgPath': imgBaseUrl+'images/advance-stock/Candlestick_Lower-High-Lower-Low.svg',
        'defaultValue': false,
        'field': 'lower_high_lower_low',
        'name': 'candlestick',
      },
      {
        'label': 'Inside Day',
        'imgPath': imgBaseUrl+'images/advance-stock/Candlestick_Inside-Day.svg',
        'defaultValue': false,
        'field': 'inside_day',
        'name': 'candlestick',
      },
      {
        'label': 'Outside Day',
        'imgPath': imgBaseUrl+'images/advance-stock/Candlestick_Outside-Day.svg',
        'defaultValue': false,
        'field': 'outside_day',
        'name': 'candlestick',
      },
    ],
  },
  {
    'title': 'Volume & Delivery',
    'data': [
      {
        'label': 'High Delivery %age',
        'imgPath': imgBaseUrl+'images/advance-stock/Volume-Delivery_High-Delivery-age.svg',
        'defaultValue': false,
        'field': 'high_delivery_age',
        'name': 'delivery',
      },
      {
        'label': 'Lowe High Delivery Quantity',
        'imgPath': imgBaseUrl+'images/advance-stock/Volume-Delivery_Lower-High-Delivery-Quantity.svg',
        'defaultValue': false,
        'field': 'lower_high_delivery_qty',
        'name': 'delivery',
      },
      {
        'label': 'High Delivery %age & Quantity',
        'imgPath': imgBaseUrl+'images/advance-stock/Volume-Delivery_High-Delivery-age-Quantity.svg',
        'defaultValue': false,
        'field': 'high_delivery_age_qty',
        'name': 'delivery',
      },
      {
        'label': 'High Trade Quantity',
        'imgPath': imgBaseUrl+'images/advance-stock/Volume-Delivery_High-Trade-Quantity.svg',
        'defaultValue': false,
        'field': 'high_trade_qty',
        'name': 'delivery',
      },
    ],
  },
  {
    'title': 'Pivots',
    'data': [
      {
        'label': 'Above R2 Resistance',
        'imgPath': imgBaseUrl+'images/advance-stock/Pivots_Above-R2-Resistance.svg',
        'defaultValue': false,
        'field': 'above_r2',
        'name': 'pivots',
      },
      {
        'label': 'Between R1 & R2',
        'imgPath': imgBaseUrl+'images/advance-stock/Pivots_Between-R1-R2.svg',
        'defaultValue': false,
        'field': 'between_r1_r2',
        'name': 'pivots',
      },
      {
        'label': 'Above Pivot',
        'imgPath': imgBaseUrl+'images/advance-stock/Pivots_Above-Pivot.svg',
        'defaultValue': false,
        'field': 'above_pivot',
        'name': 'pivots',
      },
      {
        'label': 'Below Pivot',
        'imgPath': imgBaseUrl+'images/advance-stock/Pivots_Below-Pivot.svg',
        'defaultValue': false,
        'field': 'below_pivot',
        'name': 'pivots',
      },
      {
        'label': 'Between S2 & S1',
        'imgPath': imgBaseUrl+'images/advance-stock/Pivots_Between-S2-S1.svg',
        'defaultValue': false,
        'field': 'between_s2_s1',
        'name': 'pivots',
      },
      {
        'label': 'Below S2 Support',
        'imgPath': imgBaseUrl+'images/advance-stock/Below-S2-Support.svg',
        'defaultValue': false,
        'field': 's2_support',
        'name': 'pivots',
      },
    ],
  },
  {
    'title': 'Gaps',
    'data': [
      {
        'label': 'Gap Up Opening',
        'imgPath': imgBaseUrl+'images/advance-stock/Gaps_Gap-Up-Opening.svg',
        'defaultValue': false,
        'field': 'gap_up_opening',
        'name': 'gaps',
      },
      {
        'label': 'Gap Up Opening (Gap Filled)',
        'imgPath': imgBaseUrl+'images/advance-stock/Gaps_Gap-Up-Opening(Gap-Filled).svg',
        'defaultValue': false,
        'field': 'gap_up_opening_fill',
        'name': 'gaps',
      },
      {
        'label': 'Gap Up Opening (Gap Unfilled)',
        'imgPath': imgBaseUrl+'images/advance-stock/Gaps_Gap-Up-Opening-(Gap-Unfilled).svg',
        'defaultValue': false,
        'field': 'gap_up_opening_unfill',
        'name': 'gaps',
      },
      {
        'label': 'Gap Down Opening',
        'imgPath': imgBaseUrl+'images/advance-stock/Gaps_Gap-Down-Opening.svg',
        'defaultValue': false,
        'field': 'gap_down_opening',
        'name': 'gaps',
      },
      {
        'label': 'Gap Down Opening (Gap Filled)',
        'imgPath': imgBaseUrl+'images/advance-stock/Gaps_Gap-Down-Opening(Gap-Filled).svg',
        'defaultValue': false,
        'field': 'gap_down_opening_fill',
        'name': 'gaps',
      },
      {
        'label': 'Gap Down Opening (Gap Unfilled)',
        'imgPath': imgBaseUrl+'images/advance-stock/Gaps_Gap-Down-Opening(Gap-Unfilled).svg',
        'defaultValue': false,
        'field': 'gap_down_opening_unfill',
        'name': 'gaps',
      },
    ],
  },
];

export default PriceActionVolumeValue;
