export const defaultColumns = {
  instType: true,
  expiry_date: true,
  oi: true,
  oi_value: true,
  changeOi: true,
  change_oi_value: true,
  ltp: true,
  changePer: true,
  volume: true,
  openVal: true,
  highval: true,
  lowVal: true,
  builtup: true,
  bid_price: true,
  offer_price: true,
  g_rho: false,
  g_delta: false,
  g_gamma: false,
  g_iv: false,
  g_theta: false,
  g_vega: false,
};

export const defaultTableColumns = [
  { field: 'expiry_date', heading: 'Expiry', align: 'right', status: true },
  { field: 'oi', heading: 'OI', align: 'right', status: true },
  { field: 'oi_value', heading: 'OI IN VALUE', align: 'right', status: true },
  { field: 'changeOi', heading: 'CHNG IN OI', align: 'right', status: true },
  { field: 'change_oi_value', heading: 'CHG OI IN VALUE', align: 'right', status: true },
  { field: 'ltp', heading: 'LTP', align: 'right', status: true },
  { field: 'changePer', heading: 'CHG% (CHG LTP)', align: 'right', status: true },
  { field: 'volume', heading: 'VOLUME', align: 'right', status: true },
  { field: 'openVal', heading: 'OPEN', align: 'right', status: true },
  { field: 'highval', heading: 'HIGH', align: 'right', status: true },
  { field: 'lowVal', heading: 'LOW', align: 'right', status: true },
  { field: 'builtup', heading: 'BUILTUP', status: true },
  { field: 'bid_price', heading: 'BID PRICE', align: 'right', status: true },
  { field: 'offer_price', heading: 'OFFER PRICE', align: 'right', status: true },
  { field: 'g_rho', heading: 'RHO', align: 'right', status: false },
  { field: 'g_delta', heading: 'DELTA', align: 'right', status: false },
  { field: 'g_gamma', heading: 'GAMMA', align: 'right', status: false },
  { field: 'g_iv', heading: 'IV', align: 'right', status: false },
  { field: 'g_theta', heading: 'THETA', align: 'right', status: false },
  { field: 'g_vega', heading: 'VEGA', align: 'right', status: false },
];
