export const totalStrikes = [0, 10, 20, 30, 40];

export const optionChainColumns = [
  {
    Header: 'Calls',
    columns: [
      {
        Header: 'Net Chg',
        accessor: 'calls_net_change',
        maxWidth: 400,
        width: 50,
        minWidth: 50,
      },
      {
        Header: 'Rho',
        accessor: 'call_rho',
        maxWidth: 400,
        width: 50,
        minWidth: 50,
      },
      {
        Header: 'Gamma',
        accessor: 'call_gamma',
        maxWidth: 400,
        width: 75,
        minWidth: 75,
      },
      {
        Header: 'Vega',
        accessor: 'call_vega',
        maxWidth: 400,
        width: 50,
        minWidth: 50,
      },
      {
        Header: 'Theta ',
        accessor: 'call_theta',
        maxWidth: 400,
        width: 50,
        minWidth: 50,
      },
      {
        Header: 'Delta',
        accessor: 'call_delta',
        maxWidth: 400,
        width: 50,
        minWidth: 50,
      },
      {
        Header: 'BuiltUp',
        accessor: 'calls_builtup',
        maxWidth: 400,
        width: 95,
        minWidth: 95,
      },
      {
        Header: 'Volume',
        accessor: 'calls_volume',
        maxWidth: 400,
        width: 95,
        minWidth: 95,
      },
      {
        Header: 'OI in Value',
        accessor: 'calls_oi_value',
        maxWidth: 400,
        width: 105,
        minWidth: 105,
      },
      {
        Header: 'Chg in OI Value',
        accessor: 'calls_change_oi_value',
        maxWidth: 400,
        width: 105,
        minWidth: 105,
      },
      {
        Header: 'OI',
        accessor: 'calls_oi',
        maxWidth: 400,
        width: 80,
        minWidth: 80,
      },
      {
        Header: 'Chg in OI',
        accessor: 'calls_change_oi',
        maxWidth: 400,
        width: 100,
        minWidth: 100,
      },
      {
        Header: 'IV',
        accessor: 'calls_iv',
        maxWidth: 400,
        width: 50,
        minWidth: 50,
      },
      {
        Header: 'Low',
        accessor: 'call_low',
        maxWidth: 400,
        width: 70,
        minWidth: 70,
      },
      {
        Header: 'High',
        accessor: 'call_high',
        maxWidth: 400,
        width: 70,
        minWidth: 70,
      },
      {
        Header: 'Bid Price',
        accessor: 'calls_bid_price',
        maxWidth: 400,
        width: 70,
        minWidth: 70,
      },
      {
        Header: 'Offer Price',
        accessor: 'calls_offer_price',
        maxWidth: 400,
        // width: 70,
        minWidth: 100,
      },
      {
        Header: 'VWAP',
        accessor: 'calls_average_price',
        maxWidth: 400,
        width: 70,
        minWidth: 70,
      },
      {
        Header: 'LTP (Chg %)',
        accessor: 'calls_ltp',
        maxWidth: 400,
        // width: 80,
        minWidth: 90,
      },
    ],
  },
  {
    Header: ' ',
    columns: [
      {
        Header: 'Strike',
        accessor: 'strike_price',
        maxWidth: 400,
        width: 80,
        minWidth: 80,
      },
    ],
  },
  {
    Header: 'Puts',
    columns: [
      {
        Header: 'LTP (Chg %)',
        accessor: 'puts_ltp',
        maxWidth: 400,
        // width: 80,
        minWidth: 90,
      },
      {
        Header: 'VWAP',
        accessor: 'puts_average_price',
        maxWidth: 400,
        width: 70,
        minWidth: 70,
      },
      {
        Header: 'Offer Price',
        accessor: 'puts_offer_price',
        maxWidth: 400,
        // width: 70,
        minWidth: 100,
      },
      {
        Header: 'Bid Price',
        accessor: 'puts_bid_price',
        maxWidth: 400,
        width: 70,
        minWidth: 70,
      },
      {
        Header: 'High',
        accessor: 'put_high',
        maxWidth: 400,
        width: 70,
        minWidth: 70,
      },
      {
        Header: 'Low',
        accessor: 'put_low',
        maxWidth: 400,
        width: 70,
        minWidth: 70,
      },
      {
        Header: 'IV',
        accessor: 'puts_iv',
        maxWidth: 400,
        width: 50,
        minWidth: 50,
      },
      {
        Header: 'Chg in OI',
        accessor: 'puts_change_oi',
        maxWidth: 400,
        width: 100,
        minWidth: 100,
      },
      {
        Header: 'OI',
        accessor: 'puts_oi',
        maxWidth: 400,
        width: 80,
        minWidth: 80,
      },
      {
        Header: 'Chg in OI Value',
        accessor: 'puts_change_oi_value',
        maxWidth: 400,
        // width: 115,
        minWidth: 115,
      },
      {
        Header: 'OI in Value',
        accessor: 'puts_oi_value',
        maxWidth: 400,
        // width: 105,
        minWidth: 115,
      },
      {
        Header: 'Volume',
        accessor: 'puts_volume',
        maxWidth: 400,
        width: 95,
        minWidth: 95,
      },
      {
        Header: 'BuiltUp',
        accessor: 'puts_builtup',
        maxWidth: 400,
        width: 95,
        minWidth: 95,
      },
      {
        Header: 'Delta',
        accessor: 'put_delta',
        maxWidth: 400,
        width: 50,
        minWidth: 50,
      },
      {
        Header: 'Theta ',
        accessor: 'put_theta',
        maxWidth: 400,
        width: 50,
        minWidth: 50,
      },
      {
        Header: 'Vega',
        accessor: 'put_vega',
        maxWidth: 400,
        width: 50,
        minWidth: 50,
      },
      {
        Header: 'Gamma',
        accessor: 'put_gamma',
        maxWidth: 400,
        width: 75,
        minWidth: 75,
      },
      {
        Header: 'Rho',
        accessor: 'put_rho',
        maxWidth: 400,
        width: 50,
        minWidth: 50,
      },
      {
        Header: 'PCR',
        accessor: 'pcr',
        maxWidth: 400,
        // width: 50,
        minWidth: 50,
      },
      {
        Header: 'CHG OI PCR',
        accessor: 'chngInOiPcr',
        maxWidth: 400,
        // width: 50,
        minWidth: 50,
      },
      {
        Header: 'VOLUME PCR',
        accessor: 'volPcr',
        maxWidth: 400,
        // width: 50,
        minWidth: 50,
      },
      {
        Header: 'Net Chg',
        accessor: 'puts_net_change',
        maxWidth: 400,
        width: 50,
        minWidth: 50,
      },
    ],
  },
];

export const optionSettingColumns = [
  {
    header: 'HIGH/Low',
    value: 'highLow',
    category: 'normal',
  },
  {
    header: 'Bid/Offer Price',
    value: 'bidOffer',
    category: 'normal',
  },
  // {
  //   header: 'HIGH',
  //   value: 'high',
  //   category: 'normal',
  // },
  // {
  //   header: 'LOW',
  //   value: 'low',
  //   category: 'normal',
  // },
  {
    header: 'VOL',
    value: 'vol',
    category: 'normal',
  },
  {
    header: 'VWAP',
    value: 'vwap',
    category: 'normal',
  },
  {
    header: 'CHANGE IN OI',
    value: 'changeInOi',
    category: 'normal',
  },
  {
    header: 'OI IN VALUE',
    value: 'oiValue',
    category: 'normal',
  },
  {
    header: 'CHANGE IN OI IN VALUE',
    value: 'changeInOiValue',
    category: 'normal',
  },
  {
    header: 'BUILTUP',
    value: 'builtup',
    category: 'normal',
  },
  {
    header: 'PCR',
    value: 'pcr',
    category: 'normal',
  },
  {
    header: 'CHANGE IN OI PCR',
    value: 'chngInOiPcr',
    category: 'normal',
  },
  {
    header: 'VOLUME PCR',
    value: 'volPcr',
    category: 'normal',
  },
  {
    header: 'IV',
    value: 'iv',
    category: 'normal',
  },
  {
    header: 'DELTA',
    value: 'delta',
    category: 'greeks',
  },
  {
    header: 'THETA',
    value: 'theta',
    category: 'greeks',
  },
  {
    header: 'VEGA',
    value: 'vega',
    category: 'greeks',
  },
  {
    header: 'GAMMA',
    value: 'gamma',
    category: 'greeks',
  },
  {
    header: 'RHO',
    value: 'rho',
    category: 'greeks',
  },
  {
    header: 'First Highest',
    value: 'firstHighest',
    category: 'colorCode',
  },
  {
    header: 'Second Highest',
    value: 'secondHighest',
    category: 'colorCode',
  },
  {
    header: 'Third Highest',
    value: 'thirdHighest',
    category: 'colorCode',
  },
  {
    header: 'First Lowest',
    value: 'firstLowest',
    category: 'colorCode',
  },
  {
    header: 'Second Lowest',
    value: 'secondLowest',
    category: 'colorCode',
  },
  {
    header: 'Third Lowest',
    value: 'thirdLowest',
    category: 'colorCode',
  }
];

export const defaultColumns = {
  highLow: false,
  bidOffer: false,
  high: false,
  low: false,
  vol: false,
  changeInOi: true,
  oiValue: false,
  changeInOiValue: false,
  builtup: true,
  pcr: true,
  chngInOiPcr: false,
  volPcr: false,
  iv: true,
  delta: true,
  theta: false,
  vega: false,
  gamma: false,
  rho: false,
  isLotSize: true,
  aboveATM: 0,
  belowATM: 0,
  vwap: false,
  firstHighest: true,
  secondHighest: false,
  thirdHighest: false,
  firstLowest: true,
  secondLowest: false,
  thirdLowest: false,
  firstHighestColor: '#acd6c9',
  secondHighestColor: "#acd6c9",
  thirdHighestColor: "#acd6c9",
  firstLowestColor: "#e1bcbc",
  secondLowestColor: "#e1bcbc",
  thirdLowestColor: "#e1bcbc",

};


export const optionSettingColumnsBSEOptionChain = [

  {
    header: 'Bid/Offer Price',
    value: 'bidOffer',
    category: 'normal',
  },
  {
    header: 'HIGH/Low',
    value: 'highLow',
    category: 'normal',
  },
  {
    header: 'VOL',
    value: 'vol',
    category: 'normal',
  },
  // {
  //   header: 'VWAP',
  //   value: 'vwap',
  //   category: 'normal',
  // },
  {
    header: 'CHANGE IN OI',
    value: 'changeInOi',
    category: 'normal',
  },
  {
    header: 'OI IN VALUE',
    value: 'oiValue',
    category: 'normal',
  },
  {
    header: 'CHANGE IN OI IN VALUE',
    value: 'changeInOiValue',
    category: 'normal',
  },
  {
    header: 'BUILTUP',
    value: 'builtup',
    category: 'normal',
  },
  {
    header: 'PCR',
    value: 'pcr',
    category: 'normal',
  },
  {
    header: 'CHANGE IN OI PCR',
    value: 'chngInOiPcr',
    category: 'normal',
  },
  {
    header: 'VOLUME PCR',
    value: 'volPcr',
    category: 'normal',
  },
  // {
  //   header: 'IV',
  //   value: 'iv',
  //   category: 'normal',
  // },
  // {
  //   header: 'DELTA',
  //   value: 'delta',
  //   category: 'greeks',
  // },
  // {
  //   header: 'THETA',
  //   value: 'theta',
  //   category: 'greeks',
  // },
  // {
  //   header: 'VEGA',
  //   value: 'vega',
  //   category: 'greeks',
  // },
  // {
  //   header: 'GAMMA',
  //   value: 'gamma',
  //   category: 'greeks',
  // },
  // {
  //   header: 'RHO',
  //   value: 'rho',
  //   category: 'greeks',
  // },

  {
    header: 'First Highest',
    value: 'firstHighest',
    category: 'colorCode',
  },
  {
    header: 'Second Highest',
    value: 'secondHighest',
    category: 'colorCode',
  },
  {
    header: 'Third Highest',
    value: 'thirdHighest',
    category: 'colorCode',
  },
  {
    header: 'First Lowest',
    value: 'firstLowest',
    category: 'colorCode',
  },
  {
    header: 'Second Lowest',
    value: 'secondLowest',
    category: 'colorCode',
  },
  {
    header: 'Third Lowest',
    value: 'thirdLowest',
    category: 'colorCode',
  }
];


export const defaultColumnsBSEOptionsChain = {
  highLow: false,
  bidOffer: false,
  vol: false,
  changeInOi: true,
  oiValue: false,
  changeInOiValue: false,
  builtup: true,
  pcr: true,
  chngInOiPcr: false,
  volPcr: false,
  // iv: false,
  delta: false,
  theta: false,
  vega: false,
  gamma: false,
  rho: false,
  isLotSize: true,
  aboveATM: 0,
  belowATM: 0,
  // vwap: false,
  firstHighest: true,
  secondHighest: false,
  thirdHighest: false,
  firstLowest: true,
  secondLowest: false,
  thirdLowest: false,
  firstHighestColor: '#acd6c9',
  secondHighestColor: "#acd6c9",
  thirdHighestColor: "#acd6c9",
  firstLowestColor: "#e1bcbc",
  secondLowestColor: "#e1bcbc",
  thirdLowestColor: "#e1bcbc",

};

export const optionChainColumnsBSEOptionsChain = [
  {
    Header: 'Calls',
    columns: [
      {
        Header: 'Net Chg',
        accessor: 'calls_net_change',
        maxWidth: 400,
        width: 50,
        minWidth: 50,
      },
      {
        Header: 'BuiltUp',
        accessor: 'calls_builtup',
        maxWidth: 400,
        width: 95,
        minWidth: 95,
      },
      {
        Header: 'Volume',
        accessor: 'calls_volume',
        maxWidth: 400,
        width: 95,
        minWidth: 95,
      },
      {
        Header: 'OI in Value',
        accessor: 'calls_oi_value',
        maxWidth: 400,
        width: 105,
        minWidth: 105,
      },
      {
        Header: 'Chg in OI Value',
        accessor: 'calls_change_oi_value',
        maxWidth: 400,
        width: 105,
        minWidth: 105,
      },
      {
        Header: 'OI',
        accessor: 'calls_oi',
        maxWidth: 400,
        width: 80,
        minWidth: 80,
      },
      {
        Header: 'Chg in OI',
        accessor: 'calls_change_oi',
        maxWidth: 400,
        width: 100,
        minWidth: 100,
      },
      {
        Header: 'Low',
        accessor: 'calls_low',
        maxWidth: 400,
        width: 70,
        minWidth: 70,
      },
      {
        Header: 'High',
        accessor: 'calls_high',
        maxWidth: 400,
        width: 70,
        minWidth: 70,
      },
      {
        Header: 'Bid Price',
        accessor: 'calls_bid_price',
        maxWidth: 400,
        width: 70,
        minWidth: 70,
      },
      {
        Header: 'Offer Price',
        accessor: 'calls_offer_price',
        maxWidth: 400,
        // width: 70,
        minWidth: 100,
      },
      {
        Header: 'LTP (Chg %)',
        accessor: 'calls_ltp',
        maxWidth: 400,
        // width: 80,
        minWidth: 90,
      },
    ],
  },
  {
    Header: ' ',
    columns: [
      {
        Header: 'Strike',
        accessor: 'strike_price',
        maxWidth: 400,
        width: 80,
        minWidth: 80,
      },
    ],
  },
  {
    Header: 'Puts',
    columns: [
      {
        Header: 'LTP (Chg %)',
        accessor: 'puts_ltp',
        maxWidth: 400,
        // width: 80,
        minWidth: 90,
      },

      {
        Header: 'Offer Price',
        accessor: 'puts_offer_price',
        maxWidth: 400,
        // width: 70,
        minWidth: 100,
      },
      {
        Header: 'Bid Price',
        accessor: 'puts_bid_price',
        maxWidth: 400,
        width: 70,
        minWidth: 70,
      },

      {
        Header: 'High',
        accessor: 'puts_high',
        maxWidth: 400,
        width: 70,
        minWidth: 70,
      },
      {
        Header: 'Low',
        accessor: 'puts_low',
        maxWidth: 400,
        width: 70,
        minWidth: 70,
      },
      {
        Header: 'Chg in OI',
        accessor: 'puts_change_oi',
        maxWidth: 400,
        width: 100,
        minWidth: 100,
      },
      {
        Header: 'OI',
        accessor: 'puts_oi',
        maxWidth: 400,
        width: 80,
        minWidth: 80,
      },
      {
        Header: 'Chg in OI Value',
        accessor: 'puts_change_oi_value',
        maxWidth: 400,
        // width: 115,
        minWidth: 115,
      },
      {
        Header: 'OI in Value',
        accessor: 'puts_oi_value',
        maxWidth: 400,
        // width: 105,
        minWidth: 115,
      },
      {
        Header: 'Volume',
        accessor: 'puts_volume',
        maxWidth: 400,
        width: 95,
        minWidth: 95,
      },
      {
        Header: 'BuiltUp',
        accessor: 'puts_builtup',
        maxWidth: 400,
        width: 95,
        minWidth: 95,
      },
      {
        Header: 'PCR',
        accessor: 'pcr',
        maxWidth: 400,
        // width: 50,
        minWidth: 50,
      },
      {
        Header: 'CHG OI PCR',
        accessor: 'chngInOiPcr',
        maxWidth: 400,
        // width: 50,
        minWidth: 50,
      },
      {
        Header: 'VOLUME PCR',
        accessor: 'volPcr',
        maxWidth: 400,
        // width: 50,
        minWidth: 50,
      },
      {
        Header: 'Net Chg',
        accessor: 'puts_net_change',
        maxWidth: 400,
        width: 50,
        minWidth: 50,
      },
    ],
  },
];


export const ltpCalculatorColumns = {
  highLow: false,
  bidOffer: false,
  high: false,
  low: false,
  vol: true,
  changeInOi: true,
  oiValue: false,
  changeInOiValue: false,
  builtup: true,
  pcr: true,
  chngInOiPcr: false,
  volPcr: false,
  iv: false,
  delta: true,
  theta: false,
  vega: false,
  gamma: false,
  rho: false,
  isLotSize: true,
  aboveATM: 20,
  belowATM: 20,
  vwap: false,
  firstHighest: true,
  secondHighest: false,
  thirdHighest: false,
  firstLowest: true,
  secondLowest: false,
  thirdLowest: false,
  firstHighestColor: '#acd6c9',
  secondHighestColor: "#acd6c9",
  thirdHighestColor: "#acd6c9",
  firstLowestColor: "#e1bcbc",
  secondLowestColor: "#e1bcbc",
  thirdLowestColor: "#e1bcbc",

};

export const defaultHiddenColumns = [
  'call_high',
  'put_high',
  'call_low',
  'put_low',
  'calls_bid_price',
  'puts_bid_price',
  'calls_offer_price',
  'puts_offer_price',
  'calls_change_oi_value',
  'puts_change_oi_value',
  'calls_oi_value',
  'puts_oi_value',
  'calls_volume',
  'puts_volume',
  'call_theta',
  'put_theta',
  'call_vega',
  'put_vega',
  'call_gamma',
  'put_gamma',
  'call_rho',
  'put_rho',
  'calls_net_change',
  'puts_net_change',
  'calls_average_price',
  'puts_average_price',
  'chng_in_oi_pcr',
  'volume_pcr',
];