export const pwOIDataKeys = [
  {
    title: 'Future Index Long',
    key: 'future_index_long',
    prevKey: 'prev_future_index_long',
  },
  {
    title: 'Future Index Short',
    key: 'future_index_short',
    prevKey: 'prev_future_index_short',
  },
  {
    title: 'NET',
    key: 'future_index_long,future_index_short',
    prevKey: 'prev_future_index_long,prev_future_index_short',
  },
  {
    title: 'Option Index Call Long',
    key: 'option_index_call_long',
    prevKey: 'prev_option_index_call_long',
  },
  {
    title: 'Option Index Call Short',
    key: 'option_index_call_short',
    prevKey: 'prev_option_index_call_short',
  },
  {
    title: 'NET',
    key: 'option_index_call_long,option_index_call_short',
    prevKey: 'prev_option_index_call_long,prev_option_index_call_short',
  },
  {
    title: 'Option Index Put Long',
    key: 'option_index_put_long',
    prevKey: 'prev_option_index_put_long',
  },
  {
    title: 'Option Index Put Short',
    key: 'option_index_put_short',
    prevKey: 'prev_option_index_put_short',
  },
  {
    title: 'NET',
    key: 'option_index_put_long,option_index_put_short',
    prevKey: 'prev_option_index_put_long,prev_option_index_put_short',
  },
  {
    title: 'Future Stock Long',
    key: 'future_stock_long',
    prevKey: 'prev_future_stock_long',
  },
  {
    title: 'Future Stock Short',
    key: 'future_stock_short',
    prevKey: 'prev_future_stock_short',
  },
  {
    title: 'NET',
    key: 'future_stock_long,future_stock_short',
    prevKey: 'prev_future_stock_long,prev_future_stock_short',
  },
  {
    title: 'Option Stock Call Long',
    key: 'option_stock_call_long',
    prevKey: 'prev_option_stock_call_long',
  },
  {
    title: 'Option Stock Call Short',
    key: 'option_stock_call_short',
    prevKey: 'prev_option_stock_call_short',
  },
  {
    title: 'NET',
    key: 'option_stock_call_long,option_stock_call_short',
    prevKey: 'prev_option_stock_call_long,prev_option_stock_call_short',
  },
  {
    title: 'Option Stock Put Long',
    key: 'option_stock_put_long',
    prevKey: 'prev_option_stock_put_long',
  },
  {
    title: 'Option Stock Put Short',
    key: 'option_stock_put_short',
    prevKey: 'prev_option_stock_put_short',
  },
  {
    title: 'NET',
    key: 'option_stock_put_long,option_stock_put_short',
    prevKey: 'prev_option_stock_put_long,prev_option_stock_put_short',
  },
  {
    title: 'Total Long Contracts',
    key: 'total_long_contracts',
    prevKey: 'prev_total_long_contracts',
  },
  {
    title: 'Total Short Contracts',
    key: 'total_short_contracts',
    prevKey: 'prev_total_short_contracts',
  },
  {
    title: 'NET',
    key: 'total_long_contracts,total_short_contracts',
    prevKey: 'prev_total_long_contracts,prev_total_short_contracts',
  },
];
export const pwOIData = [
  {
    title: 'Future Index Long',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'Future Index Short',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'NET',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'Option Index Call Long',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'Option Index Call Short',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'NET',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'Option Index Put Long',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'Option Index Put Short',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'NET',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'Future Stock Long',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'Future Stock Short',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'NET',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'Option Stock Call Long',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'Option Stock Call Short',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'NET',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'Option Stock Put Long',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'Option Stock Put Short',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'NET',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'Total Long Contracts',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'Total Short Contracts',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
  {
    title: 'NET',
    client: 0,
    clientChange: 0,
    dii: 0,
    diiChange: 0,
    fii: 0,
    fiiChange: 0,
    pro: 0,
    proChange: 0,
    total: 0,
    totalChange: 0,
  },
];
