export const defaultColumns = {
    market_cap: true,
    cmp: true,
    book_value: true,
    eps: true,
    stock_pe: true,
    stock_pb: true,
    roe: true,
    icr: false,
    last_year_revenue: false,
    // last_year_net_profit: false,
    npm: false,
    current_year_revenue: true,
    current_year_net_profit: true,
    _5year_revenue: false,
    _5year_revenue_profit: false,
    cogs: false,
    cogs_per: false,
    ebit: true,
    ebita: false,
    ebita_margin: false,
  };

  
  export const defaultTableColumns = [
    { field: 'market_cap', heading: 'MARKET CAP cr.', align: 'right', status: true },
    { field: 'cmp', heading: 'CMP', align: 'right', status: true },
    { field: 'book_value', heading: 'BOOK VALUE	', align: 'right', status: true },
    { field: 'eps', heading: 'EPS', align: 'right', status: true },
    { field: 'stock_pe', heading: 'STOCK P/E	', align: 'right', status: true },
    { field: 'stock_pb', heading: 'STOCK P/B', align: 'right', status: true },
    { field: 'roe', heading: 'ROE %', align: 'right', status: true },
    { field: 'icr', heading: 'ICR %', align: 'right', status: false },
    { field: 'last_year_revenue', heading: 'LAST FISCAL REVENUE', align: 'right', status: false },
    // { field: 'last_year_net_profit', heading: 'LAST FISCAL NET PROFIT', align: 'right', status: false },
    { field: 'npm', heading: 'NPM %', align: 'right', status: false },
    { field: 'current_year_revenue', heading: 'CURR. FISCAL REVENUE %', align: 'right', status: true },
    { field: 'current_year_net_profit', heading: 'CURR. FISCAL NET PROFIT %', align: 'right', status: true },
    { field: '_5year_revenue', heading: 'PAST 5 YEARS REVENUE %', align: 'right', status: false },
    { field: '_5year_revenue_profit', heading: 'PAST 5 YEARS NET PROFIT %', align: 'right', status: false },
    { field: 'cogs', heading: 'COGS', align: 'right', status: false },
    { field: 'cogs_per', heading: 'COGS %', align: 'right', status: false },
    { field: 'ebit', heading: 'EBIT', align: 'right', status: false },
    { field: 'ebita', heading: 'EBITA', align: 'right', status: true },
    { field: 'ebita_margin', heading: 'EBITA MARGIN %', align: 'right', status: false },
  ];
  